### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by glena** [auth0/wp-auth0#240]
- [ ] no se puede clicker el link de login con legacy wp
- [x] open in a new window link de ir al dashboard en settings
- [x] make the username larger by default in the db connection
- [x] actualizar la version de lock a 10.2
- [x] username style hay que agregar opcion auto que no lo setee
- [ ] checkear issue with shortcode
