### ISSUE TITLE
V5 is not available from the Wordpress plugin directory

### ISSUE THREAD

**Issue by robbytx** [auth0/wp-auth0#923]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Our Wordpress website is administered in the standard low-tech manner, where all plugins and other changes are made through the built-in Wordpress admin UI (`/wp-admin/plugins.php`).

Although version 5 has been available for [over 2 years](https://github.com/auth0/wordpress/releases/tag/5.0.0), and version 4 has been considered unsupported for [18 months](https://github.com/auth0/wordpress/commit/32de15e4e24ebc9c3b951cf59fb126598ab5ace0), the latest version available through the Wordpress admin UI (via the Wordpress plugin marketplace) is only [4.6.2](https://wordpress.org/plugins/auth0/). Also the [latest 5.x release](https://github.com/auth0/wordpress/releases/tag/5.2.1) published to GitHub are source code only -- they lack a built version of the plugin that could be downloaded and then manually uploaded through the admin UI to upgrade. Therefore, standard Wordpress installations maintained through the admin UI are effectively stuck on an unsupported version of the plugin and unable to upgrade.

Earlier this year (in May), I filed an Auth0 support ticket #02351670 requesting assistance, and I received the following response:
> Unfortunately, it's not currently possible to publish a built version in a zip file.
> Please look into using Composer for this update.
> We're working to get the Marketplace release of V5 as soon as we can.

Migrating to Composer requires significant technical expertise and investment in tooling + build/deploy infrastructure that is a much higher bar than a few clicks in the admin UI, so this requirement is a non-starter for us, as our technical expertise lies in other areas and our Wordpress site is simply used for hosting some protected content accessible to our user base (whose accounts are managed in Auth0).

Since my ticket was closed, https://community.auth0.com/t/auth0-wordpress-plugin-v4-issues/141062 was published in August recommending that users upgrade to v5 of the plugin, but without mentioning the lack of an upgrade option for users who maintain their Wordpress through the admin UI.

Since 18 months have passed since v4.x became unsupported, and 8 months have passed since Auth0 indicated a marketplace release of v5 will be available "as soon as we can", I'm filing this issue in hopes of finally gaining some traction on this.  Please let me know if I should direct this request elsewhere.

### Reproduction

Open https://wordpress.org/plugins/auth0/ and observe that version **4.6.2** is the latest version.

Open https://github.com/auth0/wordpress/releases/tag/5.2.1 and observe that the only assets are "Source code" bundles.

### wp-auth0 version

4.6.2

### WordPress version

6.7.1

### PHP version

8.3

**Comment by kishore7snehil** [comment]
@robbytx  Thanks for the heads up ! The team is looking into it and the plugin will be up soon on Marketplace.

**Comment by robbytx** [comment]
@kishore7snehil Thank you for the update.  Can this issue be left open until the plugin is published?  It's confusing to me that the issue is marked as completed when the plugin is still not available.

**Comment by kishore7snehil** [comment]
@robbytx Thanks for following up! I’ve already escalated this concern, and the team is actively working on it. There are some challenges in getting it back on the marketplace, but we are making progress.
I can’t provide a fixed date for when it will be available, but rest assured that it’s a priority for us. The issue was marked as completed because I added it to the backlog for tracking, ensuring that it remains on our radar.
I appreciate your patience, and I’ll share an update as soon as we have more information!

**Comment by davidski** [comment]
It's now two months after the last comment on this. The V5 plugin still isn't on the marketplace. Is there a better place to track this issue?
